# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e5181f781882c44a2cb80ad533a381b5bb9aaa4a14520b6811d081fb55479b3e2a51069f98c390f79acab725e0056b8540a2bdbb66ae0fa45706f816fc27943

test:
  secret_key_base: 2f99f7a63fb1bb0f3bf9c16b4e435f46c3530a1852ffc99db94f0cbd7e3631037ad0c001c86dde61e4fb218e0d234f0b70d3117a25531541a3b9e2ffa5ae4281

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
